name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install and build
        run: |
          pnpm install
          pnpm run postinstall
          pnpm run build

      - name: Publish releases
        env:
          # Disable code signing
          CSC_IDENTITY_AUTO_DISCOVERY: false
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm exec electron-builder -- --publish always --win --mac --linux
